# Generated by Django 3.0.4 on 2020-08-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durumiApp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
